export interface PPDB_KEUNGGULAN {
  number: number
  title: string
  description: string
}

export const defaultRemoteConfigValues: Record<any, any> = {
  PPDB_OPEN: false,
  PPDB_TAHUN_AJARAN: '2024-2025',
  PPDB_TOGGLE_BIAYA: true,
  PPDB_SYARAT: 'Some default requirements',
  PPDB_PROD_VERSION: '1.0.0',
  PPDB_BIAYA: 0,
  PPDB_KETERANGAN: 'Default description',
  PPDB_JADWAL: null,
  PPDB_GELOMBANG: 'Default wave',
  PPDB_DEV_VERSION: '1.0.0',
  PPDB_COMING_SOON_INFO: null,
  PPDB_BROSUR_URL: 'https://default.url',
  PPDB_BERKAS: 'Default document',
  PPDB_BANNER: 'Default banner',
  PPDB_ADDITIONAL_PROMO: 'No additional promo',
  PPDB_TOGGLE_BANNER: false,
  PPDB_TESTIMONI: null,
  PPDB_KEUNGGULAN: [] as PPDB_KEUNGGULAN[],
  PPDB_SPECIAL_PROMO: null,
}

// Define the object
export const remoteConfigs = {
  PPDB_OPEN: 'PPDB_OPEN',
  PPDB_TAHUN_AJARAN: 'PPDB_TAHUN_AJARAN',
  PPDB_TOGGLE_BIAYA: 'PPDB_TOGGLE_BIAYA',
  PPDB_SYARAT: 'PPDB_SYARAT',
  PPDB_PROD_VERSION: 'PPDB_PROD_VERSION',
  PPDB_BIAYA: 'PPDB_BIAYA',
  PPDB_KETERANGAN: 'PPDB_KETERANGAN',
  PPDB_JADWAL: 'PPDB_JADWAL',
  PPDB_GELOMBANG: 'PPDB_GELOMBANG',
  PPDB_DEV_VERSION: 'PPDB_DEV_VERSION',
  PPDB_COMING_SOON_INFO: 'PPDB_COMING_SOON_INFO',
  PPDB_BROSUR_URL: 'PPDB_BROSUR_URL',
  PPDB_BERKAS: 'PPDB_BERKAS',
  PPDB_BANNER: 'PPDB_BANNER',
  PPDB_ADDITIONAL_PROMO: 'PPDB_ADDITIONAL_PROMO',
  PPDB_TOGGLE_BANNER: 'PPDB_TOGGLE_BANNER',
  PPDB_TESTIMONI: 'PPDB_TESTIMONI',
  PPDB_KEUNGGULAN: 'PPDB_KEUNGGULAN',
  PPDB_SPECIAL_PROMO: 'PPDB_SPECIAL_PROMO',
}
