export type remoteConfigsKey =
  | "PPDB_OPEN"
  | "PPDB_TAHUN_AJARAN"
  | "PPDB_TOGGLE_BIAYA"
  | "PPDB_SYARAT"
  | "PPDB_PROD_VERSION"
  | "PPDB_BIAYA"
  | "PPDB_KETERANGAN"
  | "PPDB_JADWAL"
  | "PPDB_GELOMBANG"
  | "PPDB_DEV_VERSION"
  | "PPDB_COMING_SOON_INFO"
  | "PPDB_BROSUR_URL"
  | "PPDB_BERKAS"
  | "PPDB_BANNER"
  | "PPDB_ADDITIONAL_PROMO"

  // Define the object
export const remoteConfigs: Record<remoteConfigsKey, remoteConfigsKey> = {
    PPDB_OPEN: "PPDB_OPEN",
    PPDB_TAHUN_AJARAN: "PPDB_TAHUN_AJARAN",
    PPDB_TOGGLE_BIAYA: "PPDB_TOGGLE_BIAYA",
    PPDB_SYARAT: "PPDB_SYARAT",
    PPDB_PROD_VERSION: "PPDB_PROD_VERSION",
    PPDB_BIAYA: "PPDB_BIAYA",
    PPDB_KETERANGAN: "PPDB_KETERANGAN",
    PPDB_JADWAL: "PPDB_JADWAL",
    PPDB_GELOMBANG: "PPDB_GELOMBANG",
    PPDB_DEV_VERSION: "PPDB_DEV_VERSION",
    PPDB_COMING_SOON_INFO: "PPDB_COMING_SOON_INFO",
    PPDB_BROSUR_URL: "PPDB_BROSUR_URL",
    PPDB_BERKAS: "PPDB_BERKAS",
    PPDB_BANNER: "PPDB_BANNER",
    PPDB_ADDITIONAL_PROMO: "PPDB_ADDITIONAL_PROMO",
  };
